WORKFLOW = r"""
name: Scheduled Social Monitor

on:
  schedule:
    # runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run monitor
        env:
          LEADERS: ${{ secrets.LEADERS }}
          TARGET_URLS: ${{ secrets.TARGET_URLS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SENTIMENT_MODEL: ${{ secrets.SENTIMENT_MODEL }}
        run: |
          python monitor.py
"""

# Output: print instructions for user to split these into repo files
print("==== FILES (copy into your new GitHub repo) ====")
print("--- monitor.py ---")
print(open(__file__).read())
print("--- README.md ---")
print(README)
print("--- requirements.txt ---")
print("requests\nbeautifulsoup4\ntransformers\ntorch\n")
print("--- .github/workflows/schedule.yml ---")
print(WORKFLOW)
