name: Scheduled Social Monitor

on:
  schedule:
    # runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run monitor
        env:
          SENTIMENT_MODEL: distilbert-base-uncased-finetuned-sst-2-english
          LEADERS: ${{ secrets.LEADERS }}
          TARGET_URLS: ${{ secrets.TARGET_URLS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python monitor.py
